// txt2py_1.cpp : 定义控制台应用程序的入口点。
//

#include "stdafx.h"
#include "dataprocess.h"
#include <map>
#include <fstream>
#include <conio.h>
#include <iostream>
#include <direct.h>

using namespace std;

//决定使用哪种模式的变量
int sel = 0;

//用于解析txt中魔数magic number的意义的map对象
map<int,string> opcodemap;
map<double, string> triggerinterval;
map<int,string> startstatemap;

//出现未识别的magic number 这个flag会变化，用于编程
int iUnrecognized;

//原本打算用于提供注释的注释对象，发现编程难度会加大很多，暂时不用
comment tempcomment;

//存放全局变量的数组
vector<string> gVars;
//存放quick string的数组
vector<string> qStrs;

//各种输出文件的对象
scriptsfile scripts;
triggerfile triggers;
stringfile str_file;
troopfile trp_file;
menufile menus;
missiontplfile missions;
dialogfile dialogs;
//dlgfile中存放token-state映射 保证唯一性
map<int, string> token2state;
	
//编译需要的常量文件的对象
wofstream constantfile;
char *strstr_rep(char *source, char *old, char *ne)//字符替换  
{
	char *org = source;
	char temp[256];
	int old_length = strlen(old);//获得将被替换的字符串的大小  
	int i, j, k, location = -1;
	for (i = 0; source[i] && (location == -1); ++i)//location查找将被替换的字符串的位置  
	for (j = i, k = 0; source[j] == old[k]; j++, k++)
	if (!old[k + 1])
		location = i;
	if (location != -1)//开始替换  
	{
		for (j = 0; j < location; j++)//先把被替换的字符串的前一部分COPY到temp  
			temp[j] = source[j];
		for (i = 0; ne[i]; i++, j++)//再把替换的新字符串COPY到temp  
			temp[j] = ne[i];
		for (k = location + old_length; source[k]; k++, j++)//把剩下的内容COPY到temp  
			temp[j] = source[k];
		temp[j] = NULL;
		for (i = 0; source[i] = temp[i]; i++); //把临时字符串temp复制给source  
	}
	return org;
}
void loadquickstring(){
	ifstream ifs("quick_strings.txt");
	string tempLine;
	getline(ifs,tempLine);
	while(getline(ifs,tempLine)){
		trim(tempLine);
		if(tempLine.empty())
			continue;
		vector<string> words;
		split(tempLine," ",words);
		qStrs.push_back(words[1]);
	}
}
void initmap(){
#pragma region opcode
	opcodemap.insert(make_pair(1,"call_script"));
	opcodemap.insert(make_pair(3,"try_end"));
	opcodemap.insert(make_pair(4,"try_begin"));
	opcodemap.insert(make_pair(5,"else_try"));
	opcodemap.insert(make_pair(6,"try_for_range"));
	opcodemap.insert(make_pair(7,"try_for_range_backwards"));
	opcodemap.insert(make_pair(11,"try_for_parties"));
	opcodemap.insert(make_pair(12,"try_for_agents"));
	opcodemap.insert(make_pair(21,"store_script_param_1"));
	opcodemap.insert(make_pair(22,"store_script_param_2"));
	opcodemap.insert(make_pair(23,"store_script_param"));
	opcodemap.insert(make_pair(30,"ge"));
	opcodemap.insert(make_pair(31,"eq"));
	opcodemap.insert(make_pair(32,"gt"));
	opcodemap.insert(make_pair(33,"is_between"));
	opcodemap.insert(make_pair(36,"entering_town"));
	opcodemap.insert(make_pair(37,"map_free"));
	opcodemap.insert(make_pair(39,"encountered_party_is_attacker"));
	opcodemap.insert(make_pair(42,"conversation_screen_is_active"));
	opcodemap.insert(make_pair(44,"in_meta_mission"));
	opcodemap.insert(make_pair(47,"set_player_troop"));
	opcodemap.insert(make_pair(50,"store_repeat_object"));
	opcodemap.insert(make_pair(60,"set_result_string"));
	opcodemap.insert(make_pair(70,"key_is_down"));
	opcodemap.insert(make_pair(71,"key_clicked"));
	opcodemap.insert(make_pair(72,"game_key_is_down"));
	opcodemap.insert(make_pair(73,"game_key_clicked"));
	opcodemap.insert(make_pair(75,"mouse_get_position"));
	opcodemap.insert(make_pair(77,"omit_key_once"));
	opcodemap.insert(make_pair(78,"clear_omitted_keys"));
	opcodemap.insert(make_pair(90,"get_global_cloud_amount"));
	opcodemap.insert(make_pair(91,"set_global_cloud_amount"));
	opcodemap.insert(make_pair(92,"get_global_haze_amount"));
	opcodemap.insert(make_pair(93,"set_global_haze_amount"));
	opcodemap.insert(make_pair(101,"hero_can_join"));
	opcodemap.insert(make_pair(102,"hero_can_join_as_prisoner"));
	opcodemap.insert(make_pair(103,"party_can_join"));
	opcodemap.insert(make_pair(104,"party_can_join_as_prisoner"));
	opcodemap.insert(make_pair(105,"troops_can_join"));
	opcodemap.insert(make_pair(106,"troops_can_join_as_prisoner"));
	opcodemap.insert(make_pair(107,"party_can_join_party"));
	opcodemap.insert(make_pair(108,"party_end_battle"));
	opcodemap.insert(make_pair(110,"main_party_has_troop"));
	opcodemap.insert(make_pair(130,"party_is_in_town"));
	opcodemap.insert(make_pair(131,"party_is_in_any_town"));
	opcodemap.insert(make_pair(132,"party_is_active"));
	opcodemap.insert(make_pair(150,"player_has_item"));
	opcodemap.insert(make_pair(151,"troop_has_item_equipped"));
	opcodemap.insert(make_pair(152,"troop_is_mounted"));
	opcodemap.insert(make_pair(153,"troop_is_guarantee_ranged"));
	opcodemap.insert(make_pair(154,"troop_is_guarantee_horse"));
	opcodemap.insert(make_pair(200,"check_quest_active"));
	opcodemap.insert(make_pair(201,"check_quest_finished"));
	opcodemap.insert(make_pair(202,"check_quest_succeeded"));
	opcodemap.insert(make_pair(203,"check_quest_failed"));
	opcodemap.insert(make_pair(204,"check_quest_concluded"));
	opcodemap.insert(make_pair(250,"is_trial_version"));
	opcodemap.insert(make_pair(255,"is_edit_mode_enabled"));
	opcodemap.insert(make_pair(260,"options_get_damage_to_player"));
	opcodemap.insert(make_pair(261,"options_set_damage_to_player"));
	opcodemap.insert(make_pair(262,"options_get_damage_to_friends"));
	opcodemap.insert(make_pair(263,"options_set_damage_to_friends"));
	opcodemap.insert(make_pair(264,"options_get_combat_ai"));
	opcodemap.insert(make_pair(265,"options_set_combat_ai"));
	opcodemap.insert(make_pair(266,"options_get_campaign_ai"));
	opcodemap.insert(make_pair(267,"options_set_campaign_ai"));
	opcodemap.insert(make_pair(268,"options_get_combat_speed"));
	opcodemap.insert(make_pair(269,"options_set_combat_speed"));
	opcodemap.insert(make_pair(350,"profile_get_banner_id"));
	opcodemap.insert(make_pair(351,"profile_set_banner_id"));
	opcodemap.insert(make_pair(370,"get_achievement_stat"));
	opcodemap.insert(make_pair(371,"set_achievement_stat"));
	opcodemap.insert(make_pair(372,"unlock_achievement"));
	opcodemap.insert(make_pair(380,"send_message_to_url"));
	opcodemap.insert(make_pair(388,"multiplayer_send_message_to_server"));
	opcodemap.insert(make_pair(389,"multiplayer_send_int_to_server"));
	opcodemap.insert(make_pair(390,"multiplayer_send_2_int_to_server"));
	opcodemap.insert(make_pair(391,"multiplayer_send_3_int_to_server"));
	opcodemap.insert(make_pair(392,"multiplayer_send_4_int_to_server"));
	opcodemap.insert(make_pair(393,"multiplayer_send_string_to_server"));
	opcodemap.insert(make_pair(394,"multiplayer_send_message_to_player"));
	opcodemap.insert(make_pair(395,"multiplayer_send_int_to_player"));
	opcodemap.insert(make_pair(396,"multiplayer_send_2_int_to_player"));
	opcodemap.insert(make_pair(397,"multiplayer_send_3_int_to_player"));
	opcodemap.insert(make_pair(398,"multiplayer_send_4_int_to_player"));
	opcodemap.insert(make_pair(399,"multiplayer_send_string_to_player"));
	opcodemap.insert(make_pair(400,"get_max_players"));
	opcodemap.insert(make_pair(401,"player_is_active"));
	opcodemap.insert(make_pair(402,"player_get_team_no"));
	opcodemap.insert(make_pair(403,"player_set_team_no"));
	opcodemap.insert(make_pair(404,"player_get_troop_id"));
	opcodemap.insert(make_pair(405,"player_set_troop_id"));
	opcodemap.insert(make_pair(406,"player_get_agent_id"));
	opcodemap.insert(make_pair(407,"player_get_gold"));
	opcodemap.insert(make_pair(408,"player_set_gold"));
	opcodemap.insert(make_pair(409,"player_spawn_new_agent"));
	opcodemap.insert(make_pair(410,"player_add_spawn_item"));
	opcodemap.insert(make_pair(411,"multiplayer_get_my_team"));
	opcodemap.insert(make_pair(412,"multiplayer_get_my_troop"));
	opcodemap.insert(make_pair(413,"multiplayer_set_my_troop"));
	opcodemap.insert(make_pair(414,"multiplayer_get_my_gold"));
	opcodemap.insert(make_pair(415,"multiplayer_get_my_player"));
	opcodemap.insert(make_pair(416,"multiplayer_clear_scene"));
	opcodemap.insert(make_pair(417,"multiplayer_is_server"));
	opcodemap.insert(make_pair(418,"multiplayer_is_dedicated_server"));
	opcodemap.insert(make_pair(419,"game_in_multiplayer_mode"));
	opcodemap.insert(make_pair(420,"multiplayer_make_everyone_enemy"));
	opcodemap.insert(make_pair(421,"player_control_agent"));
	opcodemap.insert(make_pair(422,"player_get_item_id"));
	opcodemap.insert(make_pair(423,"player_get_banner_id"));
	opcodemap.insert(make_pair(424,"game_get_reduce_campaign_ai"));
	opcodemap.insert(make_pair(425,"multiplayer_find_spawn_point"));
	opcodemap.insert(make_pair(426,"set_spawn_effector_scene_prop_kind"));
	opcodemap.insert(make_pair(427,"set_spawn_effector_scene_prop_id"));
	opcodemap.insert(make_pair(429,"player_set_is_admin"));
	opcodemap.insert(make_pair(430,"player_is_admin"));
	opcodemap.insert(make_pair(431,"player_get_score"));
	opcodemap.insert(make_pair(432,"player_set_score"));
	opcodemap.insert(make_pair(433,"player_get_kill_count"));
	opcodemap.insert(make_pair(434,"player_set_kill_count"));
	opcodemap.insert(make_pair(435,"player_get_death_count"));
	opcodemap.insert(make_pair(436,"player_set_death_count"));
	opcodemap.insert(make_pair(437,"player_get_ping"));
	opcodemap.insert(make_pair(438,"player_is_busy_with_menus"));
	opcodemap.insert(make_pair(439,"player_get_is_muted"));
	opcodemap.insert(make_pair(440,"player_set_is_muted"));
	opcodemap.insert(make_pair(441,"player_get_unique_id"));
	opcodemap.insert(make_pair(442,"player_get_gender"));
	opcodemap.insert(make_pair(450,"team_get_bot_kill_count"));
	opcodemap.insert(make_pair(451,"team_set_bot_kill_count"));
	opcodemap.insert(make_pair(452,"team_get_bot_death_count"));
	opcodemap.insert(make_pair(453,"team_set_bot_death_count"));
	opcodemap.insert(make_pair(454,"team_get_kill_count"));
	opcodemap.insert(make_pair(455,"team_get_score"));
	opcodemap.insert(make_pair(456,"team_set_score"));
	opcodemap.insert(make_pair(457,"team_set_faction"));
	opcodemap.insert(make_pair(458,"team_get_faction"));
	opcodemap.insert(make_pair(459,"player_save_picked_up_items_for_next_spawn"));
	opcodemap.insert(make_pair(460,"player_get_value_of_original_items"));
	opcodemap.insert(make_pair(461,"player_item_slot_is_picked_up"));
	opcodemap.insert(make_pair(465,"kick_player"));
	opcodemap.insert(make_pair(466,"ban_player"));
	opcodemap.insert(make_pair(467,"save_ban_info_of_player"));
	opcodemap.insert(make_pair(468,"ban_player_using_saved_ban_info"));
	opcodemap.insert(make_pair(470,"start_multiplayer_mission"));
	opcodemap.insert(make_pair(473,"server_add_message_to_log"));
	opcodemap.insert(make_pair(475,"server_get_renaming_server_allowed"));
	opcodemap.insert(make_pair(476,"server_get_changing_game_type_allowed"));
	opcodemap.insert(make_pair(478,"server_get_combat_speed"));
	opcodemap.insert(make_pair(479,"server_set_combat_speed"));
	opcodemap.insert(make_pair(480,"server_get_friendly_fire"));
	opcodemap.insert(make_pair(481,"server_set_friendly_fire"));
	opcodemap.insert(make_pair(482,"server_get_control_block_dir"));
	opcodemap.insert(make_pair(483,"server_set_control_block_dir"));
	opcodemap.insert(make_pair(484,"server_set_password"));
	opcodemap.insert(make_pair(485,"server_get_add_to_game_servers_list"));
	opcodemap.insert(make_pair(486,"server_set_add_to_game_servers_list"));
	opcodemap.insert(make_pair(487,"server_get_ghost_mode"));
	opcodemap.insert(make_pair(488,"server_set_ghost_mode"));
	opcodemap.insert(make_pair(489,"server_set_name"));
	opcodemap.insert(make_pair(490,"server_get_max_num_players"));
	opcodemap.insert(make_pair(491,"server_set_max_num_players"));
	opcodemap.insert(make_pair(492,"server_set_welcome_message"));
	opcodemap.insert(make_pair(493,"server_get_melee_friendly_fire"));
	opcodemap.insert(make_pair(494,"server_set_melee_friendly_fire"));
	opcodemap.insert(make_pair(495,"server_get_friendly_fire_damage_self_ratio"));
	opcodemap.insert(make_pair(496,"server_set_friendly_fire_damage_self_ratio"));
	opcodemap.insert(make_pair(497,"server_get_friendly_fire_damage_friend_ratio"));
	opcodemap.insert(make_pair(498,"server_set_friendly_fire_damage_friend_ratio"));
	opcodemap.insert(make_pair(499,"server_get_anti_cheat"));
	opcodemap.insert(make_pair(477,"server_set_anti_cheat"));
	opcodemap.insert(make_pair(500,"troop_set_slot"));
	opcodemap.insert(make_pair(501,"party_set_slot"));
	opcodemap.insert(make_pair(502,"faction_set_slot"));
	opcodemap.insert(make_pair(503,"scene_set_slot"));
	opcodemap.insert(make_pair(504,"party_template_set_slot"));
	opcodemap.insert(make_pair(505,"agent_set_slot"));
	opcodemap.insert(make_pair(506,"quest_set_slot"));
	opcodemap.insert(make_pair(507,"item_set_slot"));
	opcodemap.insert(make_pair(508,"player_set_slot"));
	opcodemap.insert(make_pair(509,"team_set_slot"));
	opcodemap.insert(make_pair(510,"scene_prop_set_slot"));
	opcodemap.insert(make_pair(520,"troop_get_slot"));
	opcodemap.insert(make_pair(521,"party_get_slot"));
	opcodemap.insert(make_pair(522,"faction_get_slot"));
	opcodemap.insert(make_pair(523,"scene_get_slot"));
	opcodemap.insert(make_pair(524,"party_template_get_slot"));
	opcodemap.insert(make_pair(525,"agent_get_slot"));
	opcodemap.insert(make_pair(526,"quest_get_slot"));
	opcodemap.insert(make_pair(527,"item_get_slot"));
	opcodemap.insert(make_pair(528,"player_get_slot"));
	opcodemap.insert(make_pair(529,"team_get_slot"));
	opcodemap.insert(make_pair(530,"scene_prop_get_slot"));
	opcodemap.insert(make_pair(540,"troop_slot_eq"));
	opcodemap.insert(make_pair(541,"party_slot_eq"));
	opcodemap.insert(make_pair(542,"faction_slot_eq"));
	opcodemap.insert(make_pair(543,"scene_slot_eq"));
	opcodemap.insert(make_pair(544,"party_template_slot_eq"));
	opcodemap.insert(make_pair(545,"agent_slot_eq"));
	opcodemap.insert(make_pair(546,"quest_slot_eq"));
	opcodemap.insert(make_pair(547,"item_slot_eq"));
	opcodemap.insert(make_pair(548,"player_slot_eq"));
	opcodemap.insert(make_pair(549,"team_slot_eq"));
	opcodemap.insert(make_pair(550,"scene_prop_slot_eq"));
	opcodemap.insert(make_pair(560,"troop_slot_ge"));
	opcodemap.insert(make_pair(561,"party_slot_ge"));
	opcodemap.insert(make_pair(562,"faction_slot_ge"));
	opcodemap.insert(make_pair(563,"scene_slot_ge"));
	opcodemap.insert(make_pair(564,"party_template_slot_ge"));
	opcodemap.insert(make_pair(565,"agent_slot_ge"));
	opcodemap.insert(make_pair(566,"quest_slot_ge"));
	opcodemap.insert(make_pair(567,"item_slot_ge"));
	opcodemap.insert(make_pair(568,"player_slot_ge"));
	opcodemap.insert(make_pair(569,"team_slot_ge"));
	opcodemap.insert(make_pair(570,"scene_prop_slot_ge"));
	opcodemap.insert(make_pair(599,"play_sound_at_position"));
	opcodemap.insert(make_pair(600,"play_sound"));
	opcodemap.insert(make_pair(601,"play_track"));
	opcodemap.insert(make_pair(602,"play_cue_track"));
	opcodemap.insert(make_pair(603,"music_set_situation"));
	opcodemap.insert(make_pair(604,"music_set_culture"));
	opcodemap.insert(make_pair(609,"stop_all_sounds"));
	opcodemap.insert(make_pair(615,"store_last_sound_channel"));
	opcodemap.insert(make_pair(616,"stop_sound_channel"));
	opcodemap.insert(make_pair(700,"copy_position"));
	opcodemap.insert(make_pair(701,"init_position"));
	opcodemap.insert(make_pair(702,"get_trigger_object_position"));
	opcodemap.insert(make_pair(705,"get_angle_between_positions"));
	opcodemap.insert(make_pair(707,"position_has_line_of_sight_to_position"));
	opcodemap.insert(make_pair(710,"get_distance_between_positions"));
	opcodemap.insert(make_pair(711,"get_distance_between_positions_in_meters"));
	opcodemap.insert(make_pair(712,"get_sq_distance_between_positions"));
	opcodemap.insert(make_pair(713,"get_sq_distance_between_positions_in_meters"));
	opcodemap.insert(make_pair(714,"position_is_behind_position"));
	opcodemap.insert(make_pair(715,"get_sq_distance_between_position_heights"));
	opcodemap.insert(make_pair(716,"position_transform_position_to_parent"));
	opcodemap.insert(make_pair(717,"position_transform_position_to_local"));
	opcodemap.insert(make_pair(718,"position_copy_rotation"));
	opcodemap.insert(make_pair(719,"position_copy_origin"));
	opcodemap.insert(make_pair(720,"position_move_x"));
	opcodemap.insert(make_pair(721,"position_move_y"));
	opcodemap.insert(make_pair(722,"position_move_z"));
	opcodemap.insert(make_pair(723,"position_rotate_x"));
	opcodemap.insert(make_pair(724,"position_rotate_y"));
	opcodemap.insert(make_pair(725,"position_rotate_z"));
	opcodemap.insert(make_pair(726,"position_get_x"));
	opcodemap.insert(make_pair(727,"position_get_y"));
	opcodemap.insert(make_pair(728,"position_get_z"));
	opcodemap.insert(make_pair(729,"position_set_x"));
	opcodemap.insert(make_pair(730,"position_set_y"));
	opcodemap.insert(make_pair(731,"position_set_z"));
	opcodemap.insert(make_pair(735,"position_get_scale_x"));
	opcodemap.insert(make_pair(736,"position_get_scale_y"));
	opcodemap.insert(make_pair(737,"position_get_scale_z"));
	opcodemap.insert(make_pair(738,"position_rotate_x_floating"));
	opcodemap.insert(make_pair(739,"position_rotate_y_floating"));
	opcodemap.insert(make_pair(740,"position_get_rotation_around_z"));
	opcodemap.insert(make_pair(741,"position_normalize_origin"));
	opcodemap.insert(make_pair(742,"position_get_rotation_around_x"));
	opcodemap.insert(make_pair(743,"position_get_rotation_around_y"));
	opcodemap.insert(make_pair(744,"position_set_scale_x"));
	opcodemap.insert(make_pair(745,"position_set_scale_y"));
	opcodemap.insert(make_pair(746,"position_set_scale_z"));
	opcodemap.insert(make_pair(750,"position_get_screen_projection"));
	opcodemap.insert(make_pair(791,"position_set_z_to_ground_level"));
	opcodemap.insert(make_pair(792,"position_get_distance_to_terrain"));
	opcodemap.insert(make_pair(793,"position_get_distance_to_ground_level"));
	opcodemap.insert(make_pair(900,"start_presentation"));
	opcodemap.insert(make_pair(901,"start_background_presentation"));
	opcodemap.insert(make_pair(902,"presentation_set_duration"));
	opcodemap.insert(make_pair(903,"is_presentation_active"));
	opcodemap.insert(make_pair(910,"create_text_overlay"));
	opcodemap.insert(make_pair(911,"create_mesh_overlay"));
	opcodemap.insert(make_pair(912,"create_button_overlay"));
	opcodemap.insert(make_pair(913,"create_image_button_overlay"));
	opcodemap.insert(make_pair(914,"create_slider_overlay"));
	opcodemap.insert(make_pair(915,"create_progress_overlay"));
	opcodemap.insert(make_pair(916,"create_combo_button_overlay"));
	opcodemap.insert(make_pair(917,"create_text_box_overlay"));
	opcodemap.insert(make_pair(918,"create_check_box_overlay"));
	opcodemap.insert(make_pair(919,"create_simple_text_box_overlay"));
	opcodemap.insert(make_pair(920,"overlay_set_text"));
	opcodemap.insert(make_pair(921,"overlay_set_color"));
	opcodemap.insert(make_pair(922,"overlay_set_alpha"));
	opcodemap.insert(make_pair(923,"overlay_set_hilight_color"));
	opcodemap.insert(make_pair(924,"overlay_set_hilight_alpha"));
	opcodemap.insert(make_pair(925,"overlay_set_size"));
	opcodemap.insert(make_pair(926,"overlay_set_position"));
	opcodemap.insert(make_pair(927,"overlay_set_val"));
	opcodemap.insert(make_pair(928,"overlay_set_boundaries"));
	opcodemap.insert(make_pair(929,"overlay_set_area_size"));
	opcodemap.insert(make_pair(930,"overlay_set_mesh_rotation"));
	opcodemap.insert(make_pair(931,"overlay_add_item"));
	opcodemap.insert(make_pair(932,"overlay_animate_to_color"));
	opcodemap.insert(make_pair(933,"overlay_animate_to_alpha"));
	opcodemap.insert(make_pair(934,"overlay_animate_to_highlight_color"));
	opcodemap.insert(make_pair(935,"overlay_animate_to_highlight_alpha"));
	opcodemap.insert(make_pair(936,"overlay_animate_to_size"));
	opcodemap.insert(make_pair(937,"overlay_animate_to_position"));
	opcodemap.insert(make_pair(938,"create_image_button_overlay_with_tableau_material"));
	opcodemap.insert(make_pair(939,"create_mesh_overlay_with_tableau_material"));
	opcodemap.insert(make_pair(940,"create_game_button_overlay"));
	opcodemap.insert(make_pair(941,"create_in_game_button_overlay"));
	opcodemap.insert(make_pair(942,"create_number_box_overlay"));
	opcodemap.insert(make_pair(943,"create_listbox_overlay"));
	opcodemap.insert(make_pair(944,"create_mesh_overlay_with_item_id"));
	opcodemap.insert(make_pair(945,"set_container_overlay"));
	opcodemap.insert(make_pair(946,"overlay_get_position"));
	opcodemap.insert(make_pair(947,"overlay_set_display"));
	opcodemap.insert(make_pair(948,"create_combo_label_overlay"));
	opcodemap.insert(make_pair(949,"overlay_obtain_focus"));
	opcodemap.insert(make_pair(950,"overlay_set_tooltip"));
	opcodemap.insert(make_pair(951,"overlay_set_container_overlay"));
	opcodemap.insert(make_pair(952,"overlay_set_additional_render_height"));
	opcodemap.insert(make_pair(960,"show_object_details_overlay"));
	opcodemap.insert(make_pair(970,"show_item_details"));
	opcodemap.insert(make_pair(971,"close_item_details"));
	opcodemap.insert(make_pair(972,"show_item_details_with_modifier"));
	opcodemap.insert(make_pair(980,"context_menu_add_item"));
	opcodemap.insert(make_pair(990,"get_average_game_difficulty"));
	opcodemap.insert(make_pair(991,"get_level_boundary"));
	opcodemap.insert(make_pair(1003,"all_enemies_defeated"));
	opcodemap.insert(make_pair(1004,"race_completed_by_player"));
	opcodemap.insert(make_pair(1005,"num_active_teams_le"));
	opcodemap.insert(make_pair(1006,"main_hero_fallen"));
	opcodemap.insert(make_pair(2147483648,"neg"));
	opcodemap.insert(make_pair(1073741824,"this_or_next"));
	opcodemap.insert(make_pair(2147483678,"lt"));
	opcodemap.insert(make_pair(2147483679,"neq"));
	opcodemap.insert(make_pair(2147483680,"le"));
	opcodemap.insert(make_pair(1019,"finish_party_battle_mode"));
	opcodemap.insert(make_pair(1020,"set_party_battle_mode"));
	opcodemap.insert(make_pair(1021,"set_camera_follow_party"));
	opcodemap.insert(make_pair(1025,"start_map_conversation"));
	opcodemap.insert(make_pair(1030,"rest_for_hours"));
	opcodemap.insert(make_pair(1031,"rest_for_hours_interactive"));
	opcodemap.insert(make_pair(1062,"add_xp_to_troop"));
	opcodemap.insert(make_pair(1063,"add_gold_as_xp"));
	opcodemap.insert(make_pair(1064,"add_xp_as_reward"));
	opcodemap.insert(make_pair(1070,"add_gold_to_party"));
	opcodemap.insert(make_pair(1080,"set_party_creation_random_limits"));
	opcodemap.insert(make_pair(1095,"troop_set_note_available"));
	opcodemap.insert(make_pair(1096,"faction_set_note_available"));
	opcodemap.insert(make_pair(1097,"party_set_note_available"));
	opcodemap.insert(make_pair(1098,"quest_set_note_available"));
	opcodemap.insert(make_pair(1100,"spawn_around_party"));
	opcodemap.insert(make_pair(1103,"set_spawn_radius"));
	opcodemap.insert(make_pair(1104,"display_debug_message"));
	opcodemap.insert(make_pair(1105,"display_log_message"));
	opcodemap.insert(make_pair(1106,"display_message"));
	opcodemap.insert(make_pair(1107,"set_show_messages"));
	opcodemap.insert(make_pair(1108,"add_troop_note_tableau_mesh"));
	opcodemap.insert(make_pair(1109,"add_faction_note_tableau_mesh"));
	opcodemap.insert(make_pair(1110,"add_party_note_tableau_mesh"));
	opcodemap.insert(make_pair(1111,"add_quest_note_tableau_mesh"));
	opcodemap.insert(make_pair(1090,"add_info_page_note_tableau_mesh"));
	opcodemap.insert(make_pair(1114,"add_troop_note_from_dialog"));
	opcodemap.insert(make_pair(1115,"add_faction_note_from_dialog"));
	opcodemap.insert(make_pair(1116,"add_party_note_from_dialog"));
	opcodemap.insert(make_pair(1112,"add_quest_note_from_dialog"));
	opcodemap.insert(make_pair(1091,"add_info_page_note_from_dialog"));
	opcodemap.insert(make_pair(1117,"add_troop_note_from_sreg"));
	opcodemap.insert(make_pair(1118,"add_faction_note_from_sreg"));
	opcodemap.insert(make_pair(1119,"add_party_note_from_sreg"));
	opcodemap.insert(make_pair(1113,"add_quest_note_from_sreg"));
	opcodemap.insert(make_pair(1092,"add_info_page_note_from_sreg"));
	opcodemap.insert(make_pair(1120,"dialog_box"));
	opcodemap.insert(make_pair(1121,"question_box"));
	opcodemap.insert(make_pair(1122,"tutorial_message"));
	opcodemap.insert(make_pair(1123,"tutorial_message_set_position"));
	opcodemap.insert(make_pair(1124,"tutorial_message_set_size"));
	opcodemap.insert(make_pair(1125,"tutorial_message_set_center_justify"));
	opcodemap.insert(make_pair(1126,"tutorial_message_set_background"));
	opcodemap.insert(make_pair(1130,"set_tooltip_text"));
	opcodemap.insert(make_pair(1170,"reset_price_rates"));
	opcodemap.insert(make_pair(1171,"set_price_rate_for_item"));
	opcodemap.insert(make_pair(1172,"set_price_rate_for_item_type"));
	opcodemap.insert(make_pair(1201,"party_join"));
	opcodemap.insert(make_pair(1202,"party_join_as_prisoner"));
	opcodemap.insert(make_pair(1203,"troop_join"));
	opcodemap.insert(make_pair(1204,"troop_join_as_prisoner"));
	opcodemap.insert(make_pair(1210,"remove_member_from_party"));
	opcodemap.insert(make_pair(1211,"remove_regular_prisoners"));
	opcodemap.insert(make_pair(1215,"remove_troops_from_companions"));
	opcodemap.insert(make_pair(1216,"remove_troops_from_prisoners"));
	opcodemap.insert(make_pair(1225,"heal_party"));
	opcodemap.insert(make_pair(1230,"disable_party"));
	opcodemap.insert(make_pair(1231,"enable_party"));
	opcodemap.insert(make_pair(1232,"remove_party"));
	opcodemap.insert(make_pair(1233,"add_companion_party"));
	opcodemap.insert(make_pair(1250,"add_troop_to_site"));
	opcodemap.insert(make_pair(1251,"remove_troop_from_site"));
	opcodemap.insert(make_pair(1261,"modify_visitors_at_site"));
	opcodemap.insert(make_pair(1262,"reset_visitors"));
	opcodemap.insert(make_pair(1263,"set_visitor"));
	opcodemap.insert(make_pair(1264,"set_visitors"));
	opcodemap.insert(make_pair(1265,"add_visitors_to_current_scene"));
	opcodemap.insert(make_pair(1266,"scene_set_day_time"));
	opcodemap.insert(make_pair(1270,"set_relation"));
	opcodemap.insert(make_pair(1275,"faction_set_name"));
	opcodemap.insert(make_pair(1276,"faction_set_color"));
	opcodemap.insert(make_pair(1277,"faction_get_color"));
	opcodemap.insert(make_pair(1280,"start_quest"));
	opcodemap.insert(make_pair(1281,"complete_quest"));
	opcodemap.insert(make_pair(1282,"succeed_quest"));
	opcodemap.insert(make_pair(1283,"fail_quest"));
	opcodemap.insert(make_pair(1284,"cancel_quest"));
	opcodemap.insert(make_pair(1285,"set_quest_progression"));
	opcodemap.insert(make_pair(1286,"conclude_quest"));
	opcodemap.insert(make_pair(1290,"setup_quest_text"));
	opcodemap.insert(make_pair(1291,"setup_quest_giver"));
	opcodemap.insert(make_pair(1300,"start_encounter"));
	opcodemap.insert(make_pair(1301,"leave_encounter"));
	opcodemap.insert(make_pair(1302,"encounter_attack"));
	opcodemap.insert(make_pair(1303,"select_enemy"));
	opcodemap.insert(make_pair(1304,"set_passage_menu"));
	opcodemap.insert(make_pair(1305,"auto_set_meta_mission_at_end_commited"));
	opcodemap.insert(make_pair(1307,"end_current_battle"));
	opcodemap.insert(make_pair(1320,"set_mercenary_source_party"));
	opcodemap.insert(make_pair(1490,"set_merchandise_modifier_quality"));
	opcodemap.insert(make_pair(1491,"set_merchandise_max_value"));
	opcodemap.insert(make_pair(1492,"reset_item_probabilities"));
	opcodemap.insert(make_pair(1493,"set_item_probability_in_merchandise"));
	opcodemap.insert(make_pair(1501,"troop_set_name"));
	opcodemap.insert(make_pair(1502,"troop_set_plural_name"));
	opcodemap.insert(make_pair(1503,"troop_set_face_key_from_current_profile"));
	opcodemap.insert(make_pair(1505,"troop_set_type"));
	opcodemap.insert(make_pair(1506,"troop_get_type"));
	opcodemap.insert(make_pair(1507,"troop_is_hero"));
	opcodemap.insert(make_pair(1508,"troop_is_wounded"));
	opcodemap.insert(make_pair(1509,"troop_set_auto_equip"));
	opcodemap.insert(make_pair(1510,"troop_ensure_inventory_space"));
	opcodemap.insert(make_pair(1511,"troop_sort_inventory"));
	opcodemap.insert(make_pair(1512,"troop_add_merchandise"));
	opcodemap.insert(make_pair(1513,"troop_add_merchandise_with_faction"));
	opcodemap.insert(make_pair(1515,"troop_get_xp"));
	opcodemap.insert(make_pair(1516,"troop_get_class"));
	opcodemap.insert(make_pair(1517,"troop_set_class"));
	opcodemap.insert(make_pair(1520,"troop_raise_attribute"));
	opcodemap.insert(make_pair(1521,"troop_raise_skill"));
	opcodemap.insert(make_pair(1522,"troop_raise_proficiency"));
	opcodemap.insert(make_pair(1523,"troop_raise_proficiency_linear"));
	opcodemap.insert(make_pair(1525,"troop_add_proficiency_points"));
	opcodemap.insert(make_pair(1528,"troop_add_gold"));
	opcodemap.insert(make_pair(1529,"troop_remove_gold"));
	opcodemap.insert(make_pair(1530,"troop_add_item"));
	opcodemap.insert(make_pair(1531,"troop_remove_item"));
	opcodemap.insert(make_pair(1532,"troop_clear_inventory"));
	opcodemap.insert(make_pair(1533,"troop_equip_items"));
	opcodemap.insert(make_pair(1534,"troop_inventory_slot_set_item_amount"));
	opcodemap.insert(make_pair(1537,"troop_inventory_slot_get_item_amount"));
	opcodemap.insert(make_pair(1538,"troop_inventory_slot_get_item_max_amount"));
	opcodemap.insert(make_pair(1535,"troop_add_items"));
	opcodemap.insert(make_pair(1536,"troop_remove_items"));
	opcodemap.insert(make_pair(1539,"troop_loot_troop"));
	opcodemap.insert(make_pair(1540,"troop_get_inventory_capacity"));
	opcodemap.insert(make_pair(1541,"troop_get_inventory_slot"));
	opcodemap.insert(make_pair(1542,"troop_get_inventory_slot_modifier"));
	opcodemap.insert(make_pair(1543,"troop_set_inventory_slot"));
	opcodemap.insert(make_pair(1544,"troop_set_inventory_slot_modifier"));
	opcodemap.insert(make_pair(1550,"troop_set_faction"));
	opcodemap.insert(make_pair(1555,"troop_set_age"));
	opcodemap.insert(make_pair(1560,"troop_set_health"));
	opcodemap.insert(make_pair(1561,"troop_get_upgrade_troop"));
	opcodemap.insert(make_pair(1570,"item_get_type"));
	opcodemap.insert(make_pair(1601,"party_get_num_companions"));
	opcodemap.insert(make_pair(1602,"party_get_num_prisoners"));
	opcodemap.insert(make_pair(1603,"party_set_flags"));
	opcodemap.insert(make_pair(1604,"party_set_marshall"));
	opcodemap.insert(make_pair(1605,"party_set_extra_text"));
	opcodemap.insert(make_pair(1606,"party_set_aggressiveness"));
	opcodemap.insert(make_pair(1607,"party_set_courage"));
	opcodemap.insert(make_pair(1608,"party_get_current_terrain"));
	opcodemap.insert(make_pair(1609,"party_get_template_id"));
	opcodemap.insert(make_pair(1610,"party_add_members"));
	opcodemap.insert(make_pair(1611,"party_add_prisoners"));
	opcodemap.insert(make_pair(1612,"party_add_leader"));
	opcodemap.insert(make_pair(1613,"party_force_add_members"));
	opcodemap.insert(make_pair(1614,"party_force_add_prisoners"));
	opcodemap.insert(make_pair(1615,"party_remove_members"));
	opcodemap.insert(make_pair(1616,"party_remove_prisoners"));
	opcodemap.insert(make_pair(1617,"party_clear"));
	opcodemap.insert(make_pair(1618,"party_wound_members"));
	opcodemap.insert(make_pair(1619,"party_remove_members_wounded_first"));
	opcodemap.insert(make_pair(1620,"party_set_faction"));
	opcodemap.insert(make_pair(1623,"party_relocate_near_party"));
	opcodemap.insert(make_pair(1625,"party_get_position"));
	opcodemap.insert(make_pair(1626,"party_set_position"));
	opcodemap.insert(make_pair(1627,"map_get_random_position_around_position"));
	opcodemap.insert(make_pair(1628,"map_get_land_position_around_position"));
	opcodemap.insert(make_pair(1629,"map_get_water_position_around_position"));
	opcodemap.insert(make_pair(1630,"party_count_members_of_type"));
	opcodemap.insert(make_pair(1631,"party_count_companions_of_type"));
	opcodemap.insert(make_pair(1632,"party_count_prisoners_of_type"));
	opcodemap.insert(make_pair(1633,"party_get_free_companions_capacity"));
	opcodemap.insert(make_pair(1634,"party_get_free_prisoners_capacity"));
	opcodemap.insert(make_pair(1638,"party_get_ai_initiative"));
	opcodemap.insert(make_pair(1639,"party_set_ai_initiative"));
	opcodemap.insert(make_pair(1640,"party_set_ai_behavior"));
	opcodemap.insert(make_pair(1641,"party_set_ai_object"));
	opcodemap.insert(make_pair(1642,"party_set_ai_target_position"));
	opcodemap.insert(make_pair(1643,"party_set_ai_patrol_radius"));
	opcodemap.insert(make_pair(1644,"party_ignore_player"));
	opcodemap.insert(make_pair(1645,"party_set_bandit_attraction"));
	opcodemap.insert(make_pair(1646,"party_get_helpfulness"));
	opcodemap.insert(make_pair(1647,"party_set_helpfulness"));
	opcodemap.insert(make_pair(1650,"party_get_num_companion_stacks"));
	opcodemap.insert(make_pair(1651,"party_get_num_prisoner_stacks"));
	opcodemap.insert(make_pair(1652,"party_stack_get_troop_id"));
	opcodemap.insert(make_pair(1653,"party_stack_get_size"));
	opcodemap.insert(make_pair(1654,"party_stack_get_num_wounded"));
	opcodemap.insert(make_pair(1655,"party_stack_get_troop_dna"));
	opcodemap.insert(make_pair(1656,"party_prisoner_stack_get_troop_id"));
	opcodemap.insert(make_pair(1657,"party_prisoner_stack_get_size"));
	opcodemap.insert(make_pair(1658,"party_prisoner_stack_get_troop_dna"));
	opcodemap.insert(make_pair(1660,"party_attach_to_party"));
	opcodemap.insert(make_pair(1661,"party_detach"));
	opcodemap.insert(make_pair(1662,"party_collect_attachments_to_party"));
	opcodemap.insert(make_pair(1663,"party_quick_attach_to_current_battle"));
	opcodemap.insert(make_pair(1665,"party_get_cur_town"));
	opcodemap.insert(make_pair(1666,"party_leave_cur_battle"));
	opcodemap.insert(make_pair(1667,"party_set_next_battle_simulation_time"));
	opcodemap.insert(make_pair(1669,"party_set_name"));
	opcodemap.insert(make_pair(1670,"party_add_xp_to_stack"));
	opcodemap.insert(make_pair(1671,"party_get_morale"));
	opcodemap.insert(make_pair(1672,"party_set_morale"));
	opcodemap.insert(make_pair(1673,"party_upgrade_with_xp"));
	opcodemap.insert(make_pair(1674,"party_add_xp"));
	opcodemap.insert(make_pair(1675,"party_add_template"));
	opcodemap.insert(make_pair(1676,"party_set_icon"));
	opcodemap.insert(make_pair(1677,"party_set_banner_icon"));
	opcodemap.insert(make_pair(1678,"party_add_particle_system"));
	opcodemap.insert(make_pair(1679,"party_clear_particle_systems"));
	opcodemap.insert(make_pair(1680,"party_get_battle_opponent"));
	opcodemap.insert(make_pair(1681,"party_get_icon"));
	opcodemap.insert(make_pair(1682,"party_set_extra_icon"));
	opcodemap.insert(make_pair(1685,"party_get_skill_level"));
	opcodemap.insert(make_pair(1689,"agent_get_speed"));
	opcodemap.insert(make_pair(1690,"get_battle_advantage"));
	opcodemap.insert(make_pair(1691,"set_battle_advantage"));
	opcodemap.insert(make_pair(1692,"agent_refill_wielded_shield_hit_points"));
	opcodemap.insert(make_pair(1693,"agent_is_in_special_mode"));
	opcodemap.insert(make_pair(1694,"party_get_attached_to"));
	opcodemap.insert(make_pair(1695,"party_get_num_attached_parties"));
	opcodemap.insert(make_pair(1696,"party_get_attached_party_with_rank"));
	opcodemap.insert(make_pair(1697,"inflict_casualties_to_party_group"));
	opcodemap.insert(make_pair(1698,"distribute_party_among_party_group"));
	opcodemap.insert(make_pair(1699,"agent_is_routed"));
	opcodemap.insert(make_pair(1700,"get_player_agent_no"));
	opcodemap.insert(make_pair(1701,"get_player_agent_kill_count"));
	opcodemap.insert(make_pair(1702,"agent_is_alive"));
	opcodemap.insert(make_pair(1703,"agent_is_wounded"));
	opcodemap.insert(make_pair(1704,"agent_is_human"));
	opcodemap.insert(make_pair(1705,"get_player_agent_own_troop_kill_count"));
	opcodemap.insert(make_pair(1706,"agent_is_ally"));
	opcodemap.insert(make_pair(1707,"agent_is_non_player"));
	opcodemap.insert(make_pair(1708,"agent_is_defender"));
	opcodemap.insert(make_pair(1712,"agent_is_active"));
	opcodemap.insert(make_pair(1709,"agent_get_look_position"));
	opcodemap.insert(make_pair(1710,"agent_get_position"));
	opcodemap.insert(make_pair(1711,"agent_set_position"));
	opcodemap.insert(make_pair(1713,"agent_set_look_target_agent"));
	opcodemap.insert(make_pair(1714,"agent_get_horse"));
	opcodemap.insert(make_pair(1715,"agent_get_rider"));
	opcodemap.insert(make_pair(1716,"agent_get_party_id"));
	opcodemap.insert(make_pair(1717,"agent_get_entry_no"));
	opcodemap.insert(make_pair(1718,"agent_get_troop_id"));
	opcodemap.insert(make_pair(1719,"agent_get_item_id"));
	opcodemap.insert(make_pair(1720,"store_agent_hit_points"));
	opcodemap.insert(make_pair(1721,"agent_set_hit_points"));
	opcodemap.insert(make_pair(1722,"agent_deliver_damage_to_agent"));
	opcodemap.insert(make_pair(1723,"agent_get_kill_count"));
	opcodemap.insert(make_pair(1724,"agent_get_player_id"));
	opcodemap.insert(make_pair(1725,"agent_set_invulnerable_shield"));
	opcodemap.insert(make_pair(1726,"agent_get_wielded_item"));
	opcodemap.insert(make_pair(1727,"agent_get_ammo"));
	opcodemap.insert(make_pair(1728,"agent_refill_ammo"));
	opcodemap.insert(make_pair(1729,"agent_has_item_equipped"));
	opcodemap.insert(make_pair(1730,"agent_set_scripted_destination"));
	opcodemap.insert(make_pair(1731,"agent_get_scripted_destination"));
	opcodemap.insert(make_pair(1732,"agent_force_rethink"));
	opcodemap.insert(make_pair(1733,"agent_set_no_death_knock_down_only"));
	opcodemap.insert(make_pair(1734,"agent_set_horse_speed_factor"));
	opcodemap.insert(make_pair(1735,"agent_clear_scripted_mode"));
	opcodemap.insert(make_pair(1736,"agent_set_speed_limit"));
	opcodemap.insert(make_pair(1737,"agent_ai_set_always_attack_in_melee"));
	opcodemap.insert(make_pair(1738,"agent_get_simple_behavior"));
	opcodemap.insert(make_pair(1739,"agent_get_combat_state"));
	opcodemap.insert(make_pair(1740,"agent_set_animation"));
	opcodemap.insert(make_pair(1741,"agent_set_stand_animation"));
	opcodemap.insert(make_pair(1742,"agent_set_walk_forward_animation"));
	opcodemap.insert(make_pair(1743,"agent_set_animation_progress"));
	opcodemap.insert(make_pair(1744,"agent_set_look_target_position"));
	opcodemap.insert(make_pair(1745,"agent_set_attack_action"));
	opcodemap.insert(make_pair(1746,"agent_set_defend_action"));
	opcodemap.insert(make_pair(1747,"agent_set_wielded_item"));
	opcodemap.insert(make_pair(1748,"agent_set_scripted_destination_no_attack"));
	opcodemap.insert(make_pair(1749,"agent_fade_out"));
	opcodemap.insert(make_pair(1750,"agent_play_sound"));
	opcodemap.insert(make_pair(1751,"agent_start_running_away"));
	opcodemap.insert(make_pair(1752,"agent_stop_running_away"));
	opcodemap.insert(make_pair(1753,"agent_ai_set_aggressiveness"));
	opcodemap.insert(make_pair(1754,"agent_set_kick_allowed"));
	opcodemap.insert(make_pair(1755,"remove_agent"));
	opcodemap.insert(make_pair(1756,"agent_get_attached_scene_prop"));
	opcodemap.insert(make_pair(1757,"agent_set_attached_scene_prop"));
	opcodemap.insert(make_pair(1758,"agent_set_attached_scene_prop_x"));
	opcodemap.insert(make_pair(1759,"agent_set_attached_scene_prop_z"));
	opcodemap.insert(make_pair(1760,"agent_get_time_elapsed_since_removed"));
	opcodemap.insert(make_pair(1761,"agent_get_number_of_enemies_following"));
	opcodemap.insert(make_pair(1762,"agent_set_no_dynamics"));
	opcodemap.insert(make_pair(1763,"agent_get_attack_action"));
	opcodemap.insert(make_pair(1764,"agent_get_defend_action"));
	opcodemap.insert(make_pair(1765,"agent_get_group"));
	opcodemap.insert(make_pair(1766,"agent_set_group"));
	opcodemap.insert(make_pair(1767,"agent_get_action_dir"));
	opcodemap.insert(make_pair(1768,"agent_get_animation"));
	opcodemap.insert(make_pair(1769,"agent_is_in_parried_animation"));
	opcodemap.insert(make_pair(1770,"agent_get_team"));
	opcodemap.insert(make_pair(1771,"agent_set_team"));
	opcodemap.insert(make_pair(1772,"agent_get_class"));
	opcodemap.insert(make_pair(1773,"agent_get_division"));
	opcodemap.insert(make_pair(1774,"agent_unequip_item"));
	opcodemap.insert(make_pair(1775,"class_is_listening_order"));
	opcodemap.insert(make_pair(1776,"agent_set_ammo"));
	opcodemap.insert(make_pair(1777,"agent_add_offer_with_timeout"));
	opcodemap.insert(make_pair(1778,"agent_check_offer_from_agent"));
	opcodemap.insert(make_pair(1779,"agent_equip_item"));
	opcodemap.insert(make_pair(1780,"entry_point_get_position"));
	opcodemap.insert(make_pair(1781,"entry_point_set_position"));
	opcodemap.insert(make_pair(1782,"entry_point_is_auto_generated"));
	opcodemap.insert(make_pair(1783,"agent_set_division"));
	opcodemap.insert(make_pair(1784,"team_get_hold_fire_order"));
	opcodemap.insert(make_pair(1785,"team_get_movement_order"));
	opcodemap.insert(make_pair(1786,"team_get_riding_order"));
	opcodemap.insert(make_pair(1787,"team_get_weapon_usage_order"));
	opcodemap.insert(make_pair(1788,"teams_are_enemies"));
	opcodemap.insert(make_pair(1790,"team_give_order"));
	opcodemap.insert(make_pair(1791,"team_set_order_position"));
	opcodemap.insert(make_pair(1792,"team_get_leader"));
	opcodemap.insert(make_pair(1793,"team_set_leader"));
	opcodemap.insert(make_pair(1794,"team_get_order_position"));
	opcodemap.insert(make_pair(1795,"team_set_order_listener"));
	opcodemap.insert(make_pair(1796,"team_set_relation"));
	opcodemap.insert(make_pair(1797,"set_rain"));
	opcodemap.insert(make_pair(1798,"set_fog_distance"));
	opcodemap.insert(make_pair(1799,"get_scene_boundaries"));
	opcodemap.insert(make_pair(1800,"scene_prop_enable_after_time"));
	opcodemap.insert(make_pair(1801,"scene_prop_has_agent_on_it"));
	opcodemap.insert(make_pair(1802,"agent_clear_relations_with_agents"));
	opcodemap.insert(make_pair(1803,"agent_add_relation_with_agent"));
	opcodemap.insert(make_pair(1804,"agent_get_item_slot"));
	opcodemap.insert(make_pair(1805,"ai_mesh_face_group_show_hide"));
	opcodemap.insert(make_pair(1806,"agent_is_alarmed"));
	opcodemap.insert(make_pair(1807,"agent_set_is_alarmed"));
	opcodemap.insert(make_pair(1808,"agent_stop_sound"));
	opcodemap.insert(make_pair(1809,"agent_set_attached_scene_prop_y"));
	opcodemap.insert(make_pair(1810,"scene_prop_get_num_instances"));
	opcodemap.insert(make_pair(1811,"scene_prop_get_instance"));
	opcodemap.insert(make_pair(1812,"scene_prop_get_visibility"));
	opcodemap.insert(make_pair(1813,"scene_prop_set_visibility"));
	opcodemap.insert(make_pair(1814,"scene_prop_set_hit_points"));
	opcodemap.insert(make_pair(1815,"scene_prop_get_hit_points"));
	opcodemap.insert(make_pair(1816,"scene_prop_get_max_hit_points"));
	opcodemap.insert(make_pair(1817,"scene_prop_get_team"));
	opcodemap.insert(make_pair(1818,"scene_prop_set_team"));
	opcodemap.insert(make_pair(1819,"scene_prop_set_prune_time"));
	opcodemap.insert(make_pair(1820,"scene_prop_set_cur_hit_points"));
	opcodemap.insert(make_pair(1822,"scene_prop_fade_out"));
	opcodemap.insert(make_pair(1823,"scene_prop_fade_in"));
	opcodemap.insert(make_pair(1825,"agent_get_ammo_for_slot"));
	opcodemap.insert(make_pair(1826,"agent_is_in_line_of_sight"));
	opcodemap.insert(make_pair(1827,"agent_deliver_damage_to_agent_advanced"));
	opcodemap.insert(make_pair(1828,"team_get_gap_distance"));
	opcodemap.insert(make_pair(1829,"add_missile"));
	opcodemap.insert(make_pair(1830,"scene_item_get_num_instances"));
	opcodemap.insert(make_pair(1831,"scene_item_get_instance"));
	opcodemap.insert(make_pair(1832,"scene_spawned_item_get_num_instances"));
	opcodemap.insert(make_pair(1833,"scene_spawned_item_get_instance"));
	opcodemap.insert(make_pair(1834,"scene_allows_mounted_units"));
	opcodemap.insert(make_pair(1837,"class_set_name"));
	opcodemap.insert(make_pair(1838,"prop_instance_is_valid"));
	opcodemap.insert(make_pair(1840,"prop_instance_get_variation_id"));
	opcodemap.insert(make_pair(1841,"prop_instance_get_variation_id_2"));
	opcodemap.insert(make_pair(1850,"prop_instance_get_position"));
	opcodemap.insert(make_pair(1851,"prop_instance_get_starting_position"));
	opcodemap.insert(make_pair(1852,"prop_instance_get_scale"));
	opcodemap.insert(make_pair(1853,"prop_instance_get_scene_prop_kind"));
	opcodemap.insert(make_pair(1854,"prop_instance_set_scale"));
	opcodemap.insert(make_pair(1855,"prop_instance_set_position"));
	opcodemap.insert(make_pair(1860,"prop_instance_animate_to_position"));
	opcodemap.insert(make_pair(1861,"prop_instance_stop_animating"));
	opcodemap.insert(make_pair(1862,"prop_instance_is_animating"));
	opcodemap.insert(make_pair(1863,"prop_instance_get_animation_target_position"));
	opcodemap.insert(make_pair(1864,"prop_instance_enable_physics"));
	opcodemap.insert(make_pair(1865,"prop_instance_rotate_to_position"));
	opcodemap.insert(make_pair(1866,"prop_instance_initialize_rotation_angles"));
	opcodemap.insert(make_pair(1870,"prop_instance_refill_hit_points"));
	opcodemap.insert(make_pair(1871,"prop_instance_dynamics_set_properties"));
	opcodemap.insert(make_pair(1872,"prop_instance_dynamics_set_velocity"));
	opcodemap.insert(make_pair(1873,"prop_instance_dynamics_set_omega"));
	opcodemap.insert(make_pair(1874,"prop_instance_dynamics_apply_impulse"));
	opcodemap.insert(make_pair(1877,"prop_instance_receive_damage"));
	opcodemap.insert(make_pair(1880,"prop_instance_intersects_with_prop_instance"));
	opcodemap.insert(make_pair(1881,"prop_instance_play_sound"));
	opcodemap.insert(make_pair(1882,"prop_instance_stop_sound"));
	opcodemap.insert(make_pair(1885,"prop_instance_clear_attached_missiles"));
	opcodemap.insert(make_pair(1886,"prop_instance_add_particle_system"));
	opcodemap.insert(make_pair(1887,"prop_instance_stop_all_particle_systems"));
	opcodemap.insert(make_pair(1889,"replace_prop_instance"));
	opcodemap.insert(make_pair(1890,"replace_scene_props"));
	opcodemap.insert(make_pair(1891,"replace_scene_items_with_scene_props"));
	opcodemap.insert(make_pair(1906,"set_mission_result"));
	opcodemap.insert(make_pair(1907,"finish_mission"));
	opcodemap.insert(make_pair(1910,"jump_to_scene"));
	opcodemap.insert(make_pair(1911,"set_jump_mission"));
	opcodemap.insert(make_pair(1912,"set_jump_entry"));
	opcodemap.insert(make_pair(1920,"start_mission_conversation"));
	opcodemap.insert(make_pair(1930,"add_reinforcements_to_entry"));
	opcodemap.insert(make_pair(1935,"mission_enable_talk"));
	opcodemap.insert(make_pair(1936,"mission_disable_talk"));
	opcodemap.insert(make_pair(1940,"mission_tpl_entry_set_override_flags"));
	opcodemap.insert(make_pair(1941,"mission_tpl_entry_clear_override_items"));
	opcodemap.insert(make_pair(1942,"mission_tpl_entry_add_override_item"));
	opcodemap.insert(make_pair(1950,"set_current_color"));
	opcodemap.insert(make_pair(1955,"set_position_delta"));
	opcodemap.insert(make_pair(1960,"add_point_light"));
	opcodemap.insert(make_pair(1961,"add_point_light_to_entity"));
	opcodemap.insert(make_pair(1965,"particle_system_add_new"));
	opcodemap.insert(make_pair(1968,"particle_system_emit"));
	opcodemap.insert(make_pair(1969,"particle_system_burst"));
	opcodemap.insert(make_pair(1970,"set_spawn_position"));
	opcodemap.insert(make_pair(1971,"spawn_item"));
	opcodemap.insert(make_pair(1972,"spawn_agent"));
	opcodemap.insert(make_pair(1973,"spawn_horse"));
	opcodemap.insert(make_pair(1974,"spawn_scene_prop"));
	opcodemap.insert(make_pair(1975,"particle_system_burst_no_sync"));
	opcodemap.insert(make_pair(1976,"spawn_item_without_refill"));
	opcodemap.insert(make_pair(1977,"agent_get_item_cur_ammo"));
	opcodemap.insert(make_pair(1980,"cur_tableau_add_tableau_mesh"));
	opcodemap.insert(make_pair(1981,"cur_item_set_tableau_material"));
	opcodemap.insert(make_pair(1982,"cur_scene_prop_set_tableau_material"));
	opcodemap.insert(make_pair(1983,"cur_map_icon_set_tableau_material"));
	opcodemap.insert(make_pair(1984,"cur_tableau_render_as_alpha_mask"));
	opcodemap.insert(make_pair(1985,"cur_tableau_set_background_color"));
	opcodemap.insert(make_pair(1986,"cur_agent_set_banner_tableau_material"));
	opcodemap.insert(make_pair(1987,"cur_tableau_set_ambient_light"));
	opcodemap.insert(make_pair(1988,"cur_tableau_set_camera_position"));
	opcodemap.insert(make_pair(1989,"cur_tableau_set_camera_parameters"));
	opcodemap.insert(make_pair(1990,"cur_tableau_add_point_light"));
	opcodemap.insert(make_pair(1991,"cur_tableau_add_sun_light"));
	opcodemap.insert(make_pair(1992,"cur_tableau_add_mesh"));
	opcodemap.insert(make_pair(1993,"cur_tableau_add_mesh_with_vertex_color"));
	opcodemap.insert(make_pair(1994,"cur_tableau_add_map_icon"));
	opcodemap.insert(make_pair(1995,"cur_tableau_add_troop"));
	opcodemap.insert(make_pair(1996,"cur_tableau_add_horse"));
	opcodemap.insert(make_pair(1997,"cur_tableau_set_override_flags"));
	opcodemap.insert(make_pair(1998,"cur_tableau_clear_override_items"));
	opcodemap.insert(make_pair(1999,"cur_tableau_add_override_item"));
	opcodemap.insert(make_pair(2000,"cur_tableau_add_mesh_with_scale_and_vertex_color"));
	opcodemap.insert(make_pair(2001,"mission_cam_set_mode"));
	opcodemap.insert(make_pair(2002,"mission_get_time_speed"));
	opcodemap.insert(make_pair(2003,"mission_set_time_speed"));
	opcodemap.insert(make_pair(2004,"mission_time_speed_move_to_value"));
	opcodemap.insert(make_pair(2006,"mission_set_duel_mode"));
	opcodemap.insert(make_pair(2008,"mission_cam_set_screen_color"));
	opcodemap.insert(make_pair(2009,"mission_cam_animate_to_screen_color"));
	opcodemap.insert(make_pair(2010,"mission_cam_get_position"));
	opcodemap.insert(make_pair(2011,"mission_cam_set_position"));
	opcodemap.insert(make_pair(2012,"mission_cam_animate_to_position"));
	opcodemap.insert(make_pair(2013,"mission_cam_get_aperture"));
	opcodemap.insert(make_pair(2014,"mission_cam_set_aperture"));
	opcodemap.insert(make_pair(2015,"mission_cam_animate_to_aperture"));
	opcodemap.insert(make_pair(2016,"mission_cam_animate_to_position_and_aperture"));
	opcodemap.insert(make_pair(2017,"mission_cam_set_target_agent"));
	opcodemap.insert(make_pair(2018,"mission_cam_clear_target_agent"));
	opcodemap.insert(make_pair(2019,"mission_cam_set_animation"));
	opcodemap.insert(make_pair(2020,"talk_info_show"));
	opcodemap.insert(make_pair(2021,"talk_info_set_relation_bar"));
	opcodemap.insert(make_pair(2022,"talk_info_set_line"));
	opcodemap.insert(make_pair(2031,"set_background_mesh"));
	opcodemap.insert(make_pair(2032,"set_game_menu_tableau_mesh"));
	opcodemap.insert(make_pair(2040,"change_screen_return"));
	opcodemap.insert(make_pair(2041,"change_screen_loot"));
	opcodemap.insert(make_pair(2042,"change_screen_trade"));
	opcodemap.insert(make_pair(2043,"change_screen_exchange_members"));
	opcodemap.insert(make_pair(2044,"change_screen_trade_prisoners"));
	opcodemap.insert(make_pair(2045,"change_screen_buy_mercenaries"));
	opcodemap.insert(make_pair(2046,"change_screen_view_character"));
	opcodemap.insert(make_pair(2047,"change_screen_training"));
	opcodemap.insert(make_pair(2048,"change_screen_mission"));
	opcodemap.insert(make_pair(2049,"change_screen_map_conversation"));
	opcodemap.insert(make_pair(2050,"change_screen_exchange_with_party"));
	opcodemap.insert(make_pair(2051,"change_screen_equip_other"));
	opcodemap.insert(make_pair(2052,"change_screen_map"));
	opcodemap.insert(make_pair(2053,"change_screen_notes"));
	opcodemap.insert(make_pair(2055,"change_screen_quit"));
	opcodemap.insert(make_pair(2056,"change_screen_give_members"));
	opcodemap.insert(make_pair(2057,"change_screen_controls"));
	opcodemap.insert(make_pair(2058,"change_screen_options"));
	opcodemap.insert(make_pair(2060,"jump_to_menu"));
	opcodemap.insert(make_pair(2061,"disable_menu_option"));
	opcodemap.insert(make_pair(2070,"store_trigger_param"));
	opcodemap.insert(make_pair(2071,"store_trigger_param_1"));
	opcodemap.insert(make_pair(2072,"store_trigger_param_2"));
	opcodemap.insert(make_pair(2073,"store_trigger_param_3"));
	opcodemap.insert(make_pair(2075,"set_trigger_result"));
	opcodemap.insert(make_pair(2080,"agent_ai_get_look_target"));
	opcodemap.insert(make_pair(2081,"agent_ai_get_move_target"));
	opcodemap.insert(make_pair(2082,"agent_ai_get_behavior_target"));
	opcodemap.insert(make_pair(2083,"agent_ai_set_can_crouch"));
	opcodemap.insert(make_pair(2090,"agent_set_max_hit_points"));
	opcodemap.insert(make_pair(2091,"agent_set_damage_modifier"));
	opcodemap.insert(make_pair(2092,"agent_set_accuracy_modifier"));
	opcodemap.insert(make_pair(2093,"agent_set_speed_modifier"));
	opcodemap.insert(make_pair(2094,"agent_set_reload_speed_modifier"));
	opcodemap.insert(make_pair(2095,"agent_set_use_speed_modifier"));
	opcodemap.insert(make_pair(2096,"agent_set_visibility"));
	opcodemap.insert(make_pair(2097,"agent_get_crouch_mode"));
	opcodemap.insert(make_pair(2098,"agent_set_crouch_mode"));
	opcodemap.insert(make_pair(2099,"agent_set_ranged_damage_modifier"));
	opcodemap.insert(make_pair(2100,"val_lshift"));
	opcodemap.insert(make_pair(2101,"val_rshift"));
	opcodemap.insert(make_pair(2105,"val_add"));
	opcodemap.insert(make_pair(2106,"val_sub"));
	opcodemap.insert(make_pair(2107,"val_mul"));
	opcodemap.insert(make_pair(2108,"val_div"));
	opcodemap.insert(make_pair(2109,"val_mod"));
	opcodemap.insert(make_pair(2110,"val_min"));
	opcodemap.insert(make_pair(2111,"val_max"));
	opcodemap.insert(make_pair(2112,"val_clamp"));
	opcodemap.insert(make_pair(2113,"val_abs"));
	opcodemap.insert(make_pair(2114,"val_or"));
	opcodemap.insert(make_pair(2115,"val_and"));
	opcodemap.insert(make_pair(2116,"store_or"));
	opcodemap.insert(make_pair(2117,"store_and"));
	opcodemap.insert(make_pair(2119,"store_mod"));
	opcodemap.insert(make_pair(2120,"store_add"));
	opcodemap.insert(make_pair(2121,"store_sub"));
	opcodemap.insert(make_pair(2122,"store_mul"));
	opcodemap.insert(make_pair(2123,"store_div"));
	opcodemap.insert(make_pair(2124,"set_fixed_point_multiplier"));
	opcodemap.insert(make_pair(2125,"store_sqrt"));
	opcodemap.insert(make_pair(2126,"store_pow"));
	opcodemap.insert(make_pair(2127,"store_sin"));
	opcodemap.insert(make_pair(2128,"store_cos"));
	opcodemap.insert(make_pair(2129,"store_tan"));
	opcodemap.insert(make_pair(2130,"convert_to_fixed_point"));
	opcodemap.insert(make_pair(2131,"convert_from_fixed_point"));
	opcodemap.insert(make_pair(2133,"assign"));
	opcodemap.insert(make_pair(2134,"shuffle_range"));
	opcodemap.insert(make_pair(2135,"store_random"));
	opcodemap.insert(make_pair(2136,"store_random_in_range"));
	opcodemap.insert(make_pair(2140,"store_asin"));
	opcodemap.insert(make_pair(2141,"store_acos"));
	opcodemap.insert(make_pair(2142,"store_atan"));
	opcodemap.insert(make_pair(2143,"store_atan2"));
	opcodemap.insert(make_pair(2149,"store_troop_gold"));
	opcodemap.insert(make_pair(2154,"store_num_free_stacks"));
	opcodemap.insert(make_pair(2155,"store_num_free_prisoner_stacks"));
	opcodemap.insert(make_pair(2156,"store_party_size"));
	opcodemap.insert(make_pair(2157,"store_party_size_wo_prisoners"));
	opcodemap.insert(make_pair(2158,"store_troop_kind_count"));
	opcodemap.insert(make_pair(2159,"store_num_regular_prisoners"));
	opcodemap.insert(make_pair(2160,"store_troop_count_companions"));
	opcodemap.insert(make_pair(2161,"store_troop_count_prisoners"));
	opcodemap.insert(make_pair(2165,"store_item_kind_count"));
	opcodemap.insert(make_pair(2167,"store_free_inventory_capacity"));
	opcodemap.insert(make_pair(2170,"store_skill_level"));
	opcodemap.insert(make_pair(2171,"store_character_level"));
	opcodemap.insert(make_pair(2172,"store_attribute_level"));
	opcodemap.insert(make_pair(2173,"store_troop_faction"));
	opcodemap.insert(make_pair(2173,"store_faction_of_troop"));
	opcodemap.insert(make_pair(2175,"store_troop_health"));
	opcodemap.insert(make_pair(2176,"store_proficiency_level"));
	opcodemap.insert(make_pair(2190,"store_relation"));
	opcodemap.insert(make_pair(2197,"set_conversation_speaker_troop"));
	opcodemap.insert(make_pair(2198,"set_conversation_speaker_agent"));
	opcodemap.insert(make_pair(2199,"store_conversation_agent"));
	opcodemap.insert(make_pair(2200,"store_conversation_troop"));
	opcodemap.insert(make_pair(2201,"store_partner_faction"));
	opcodemap.insert(make_pair(2202,"store_encountered_party"));
	opcodemap.insert(make_pair(2203,"store_encountered_party2"));
	opcodemap.insert(make_pair(2204,"store_faction_of_party"));
	opcodemap.insert(make_pair(2205,"set_encountered_party"));
	opcodemap.insert(make_pair(2211,"store_current_scene"));
	opcodemap.insert(make_pair(2220,"store_zoom_amount"));
	opcodemap.insert(make_pair(2221,"set_zoom_amount"));
	opcodemap.insert(make_pair(2222,"is_zoom_disabled"));
	opcodemap.insert(make_pair(2230,"store_item_value"));
	opcodemap.insert(make_pair(2231,"store_troop_value"));
	opcodemap.insert(make_pair(2240,"store_partner_quest"));
	opcodemap.insert(make_pair(2250,"store_random_quest_in_range"));
	opcodemap.insert(make_pair(2251,"store_random_troop_to_raise"));
	opcodemap.insert(make_pair(2252,"store_random_troop_to_capture"));
	opcodemap.insert(make_pair(2254,"store_random_party_in_range"));
	opcodemap.insert(make_pair(2255,"store01_random_parties_in_range"));
	opcodemap.insert(make_pair(2257,"store_random_horse"));
	opcodemap.insert(make_pair(2258,"store_random_equipment"));
	opcodemap.insert(make_pair(2259,"store_random_armor"));
	opcodemap.insert(make_pair(2261,"store_quest_number"));
	opcodemap.insert(make_pair(2262,"store_quest_item"));
	opcodemap.insert(make_pair(2263,"store_quest_troop"));
	opcodemap.insert(make_pair(2270,"store_current_hours"));
	opcodemap.insert(make_pair(2271,"store_time_of_day"));
	opcodemap.insert(make_pair(2272,"store_current_day"));
	opcodemap.insert(make_pair(2273,"is_currently_night"));
	opcodemap.insert(make_pair(2281,"store_distance_to_party_from_party"));
	opcodemap.insert(make_pair(2290,"get_party_ai_behavior"));
	opcodemap.insert(make_pair(2291,"get_party_ai_object"));
	opcodemap.insert(make_pair(2292,"party_get_ai_target_position"));
	opcodemap.insert(make_pair(2293,"get_party_ai_current_behavior"));
	opcodemap.insert(make_pair(2294,"get_party_ai_current_object"));
	opcodemap.insert(make_pair(2300,"store_num_parties_created"));
	opcodemap.insert(make_pair(2301,"store_num_parties_destroyed"));
	opcodemap.insert(make_pair(2302,"store_num_parties_destroyed_by_player"));
	opcodemap.insert(make_pair(2310,"store_num_parties_of_template"));
	opcodemap.insert(make_pair(2311,"store_random_party_of_template"));
	opcodemap.insert(make_pair(2318,"str_is_empty"));
	opcodemap.insert(make_pair(2319,"str_clear"));
	opcodemap.insert(make_pair(2320,"str_store_string"));
	opcodemap.insert(make_pair(2321,"str_store_string_reg"));
	opcodemap.insert(make_pair(2322,"str_store_troop_name"));
	opcodemap.insert(make_pair(2323,"str_store_troop_name_plural"));
	opcodemap.insert(make_pair(2324,"str_store_troop_name_by_count"));
	opcodemap.insert(make_pair(2325,"str_store_item_name"));
	opcodemap.insert(make_pair(2326,"str_store_item_name_plural"));
	opcodemap.insert(make_pair(2327,"str_store_item_name_by_count"));
	opcodemap.insert(make_pair(2330,"str_store_party_name"));
	opcodemap.insert(make_pair(2332,"str_store_agent_name"));
	opcodemap.insert(make_pair(2335,"str_store_faction_name"));
	opcodemap.insert(make_pair(2336,"str_store_quest_name"));
	opcodemap.insert(make_pair(2337,"str_store_info_page_name"));
	opcodemap.insert(make_pair(2340,"str_store_date"));
	opcodemap.insert(make_pair(2341,"str_store_troop_name_link"));
	opcodemap.insert(make_pair(2342,"str_store_party_name_link"));
	opcodemap.insert(make_pair(2343,"str_store_faction_name_link"));
	opcodemap.insert(make_pair(2344,"str_store_quest_name_link"));
	opcodemap.insert(make_pair(2345,"str_store_info_page_name_link"));
	opcodemap.insert(make_pair(2346,"str_store_class_name"));
	opcodemap.insert(make_pair(2350,"str_store_player_username"));
	opcodemap.insert(make_pair(2351,"str_store_server_password"));
	opcodemap.insert(make_pair(2352,"str_store_server_name"));
	opcodemap.insert(make_pair(2353,"str_store_welcome_message"));
	opcodemap.insert(make_pair(2355,"str_encode_url"));
	opcodemap.insert(make_pair(2360,"store_remaining_team_no"));
	opcodemap.insert(make_pair(2365,"store_mission_timer_a_msec"));
	opcodemap.insert(make_pair(2366,"store_mission_timer_b_msec"));
	opcodemap.insert(make_pair(2367,"store_mission_timer_c_msec"));
	opcodemap.insert(make_pair(2370,"store_mission_timer_a"));
	opcodemap.insert(make_pair(2371,"store_mission_timer_b"));
	opcodemap.insert(make_pair(2372,"store_mission_timer_c"));
	opcodemap.insert(make_pair(2375,"reset_mission_timer_a"));
	opcodemap.insert(make_pair(2376,"reset_mission_timer_b"));
	opcodemap.insert(make_pair(2377,"reset_mission_timer_c"));
	opcodemap.insert(make_pair(2379,"set_cheer_at_no_enemy"));
	opcodemap.insert(make_pair(2380,"store_enemy_count"));
	opcodemap.insert(make_pair(2381,"store_friend_count"));
	opcodemap.insert(make_pair(2382,"store_ally_count"));
	opcodemap.insert(make_pair(2383,"store_defender_count"));
	opcodemap.insert(make_pair(2384,"store_attacker_count"));
	opcodemap.insert(make_pair(2385,"store_normalized_team_count"));
	opcodemap.insert(make_pair(2386,"set_postfx"));
	opcodemap.insert(make_pair(2387,"set_river_shader_to_mud"));
	opcodemap.insert(make_pair(2388,"show_troop_details"));
	opcodemap.insert(make_pair(2389,"set_skybox"));
	opcodemap.insert(make_pair(2390,"set_startup_sun_light"));
	opcodemap.insert(make_pair(2391,"set_startup_ambient_light"));
	opcodemap.insert(make_pair(2392,"set_startup_ground_ambient_light"));
	opcodemap.insert(make_pair(2393,"rebuild_shadow_map"));
	opcodemap.insert(make_pair(2400,"set_shader_param_int"));
	opcodemap.insert(make_pair(2401,"set_shader_param_float"));
	opcodemap.insert(make_pair(2402,"set_shader_param_float4"));
	opcodemap.insert(make_pair(2403,"set_shader_param_float4x4"));
#pragma endregion
#pragma region startstate
	startstatemap.insert(make_pair(0x00000fff,"anyone"));
	startstatemap.insert(make_pair(0x00001000,"repeat_for_factions"));
	startstatemap.insert(make_pair(0x00002000,"repeat_for_parties"));
	startstatemap.insert(make_pair(0x00003000,"repeat_for_troops"));
	startstatemap.insert(make_pair(0x00004000,"repeat_for_100"));
	startstatemap.insert(make_pair(0x00005000,"repeat_for_1000"));
	startstatemap.insert(make_pair(0x00010000,"plyr"));
	startstatemap.insert(make_pair(0x00020000,"party_tpl"));
	startstatemap.insert(make_pair(0x00040000,"auto_proceed"));
	startstatemap.insert(make_pair(0x00080000,"multi_line"));
#pragma endregion
#pragma region triggerinterval
	triggerinterval.insert(make_pair(-5, "ti_simulate_battle"));
	triggerinterval.insert(make_pair(-6, "ti_on_party_encounter"));
	triggerinterval.insert(make_pair(-8, "ti_question_answered"));
	triggerinterval.insert(make_pair(-15, "ti_server_player_joined"));
	triggerinterval.insert(make_pair(-16, "ti_on_multiplayer_mission_end"));
	triggerinterval.insert(make_pair(-19, "ti_before_mission_start"));
	triggerinterval.insert(make_pair(-20, "ti_after_mission_start"));
	triggerinterval.insert(make_pair(-21, "ti_tab_pressed"));
	triggerinterval.insert(make_pair(-22, "ti_inventory_key_pressed"));
	triggerinterval.insert(make_pair(-23, "ti_escape_pressed"));
	triggerinterval.insert(make_pair(-24, "ti_battle_window_opened"));
	triggerinterval.insert(make_pair(-25, "ti_on_agent_spawn"));
	triggerinterval.insert(make_pair(-26, "ti_on_agent_killed_or_wounded"));
	triggerinterval.insert(make_pair(-27, "ti_on_agent_knocked_down"));
	triggerinterval.insert(make_pair(-28, "ti_on_agent_hit"));
	triggerinterval.insert(make_pair(-29, "ti_on_player_exit"));
	triggerinterval.insert(make_pair(-30, "ti_on_leave_area"));
	triggerinterval.insert(make_pair(-40, "ti_on_scene_prop_init"));
	triggerinterval.insert(make_pair(-42, "ti_on_scene_prop_hit"));
	triggerinterval.insert(make_pair(-43, "ti_on_scene_prop_destroy"));
	triggerinterval.insert(make_pair(-44, "ti_on_scene_prop_use"));
	triggerinterval.insert(make_pair(-45, "ti_on_scene_prop_is_animating"));
	triggerinterval.insert(make_pair(-46, "ti_on_scene_prop_animation_finished"));
	triggerinterval.insert(make_pair(-47, "ti_on_scene_prop_start_use"));
	triggerinterval.insert(make_pair(-48, "ti_on_scene_prop_cancel_use"));
	triggerinterval.insert(make_pair(-50, "ti_on_init_item"));
	triggerinterval.insert(make_pair(-51, "ti_on_weapon_attack"));
	triggerinterval.insert(make_pair(-52, "ti_on_missile_hit"));
	triggerinterval.insert(make_pair(-53, "ti_on_item_picked_up"));
	triggerinterval.insert(make_pair(-54, "ti_on_item_dropped"));
	triggerinterval.insert(make_pair(-55, "ti_on_agent_mount"));
	triggerinterval.insert(make_pair(-56, "ti_on_agent_dismount"));
	triggerinterval.insert(make_pair(-57, "ti_on_item_wielded"));
	triggerinterval.insert(make_pair(-58, "ti_on_item_unwielded"));
	triggerinterval.insert(make_pair(-60, "ti_on_presentation_load"));
	triggerinterval.insert(make_pair(-61, "ti_on_presentation_run"));
	triggerinterval.insert(make_pair(-62, "ti_on_presentation_event_state_change"));
	triggerinterval.insert(make_pair(-63, "ti_on_presentation_mouse_enter_leave"));
	triggerinterval.insert(make_pair(-64, "ti_on_presentation_mouse_press"));
	triggerinterval.insert(make_pair(-70, "ti_on_init_map_icon"));
	triggerinterval.insert(make_pair(-71, "ti_on_order_issued"));
	triggerinterval.insert(make_pair(100000000, "ti_once"));
#pragma endregion
}
//输出常量用来表示常量硬编码的常量
void outputconstant(){
	constantfile << "VAR             =  2<<56\n";
	constantfile << "STRING          =  3<<56\n";
	constantfile << "ITEM            =  4<<56\n";
	constantfile << "TROOP           =  5<<56\n";
	constantfile << "FACTION         =  6<<56\n";
	constantfile << "QUEST           =  7<<56\n";
	constantfile << "PARTY_TPL       =  8<<56\n";
	constantfile << "PARTY           =  9<<56\n";
	constantfile << "SCENE           = 10<<56\n";
	constantfile << "MISSION_TPL     = 11<<56\n";
	constantfile << "MENU            = 12<<56\n";
	constantfile << "SCRIPT          = 13<<56\n";
	constantfile << "PARTICLE_SYS    = 14<<56\n";
	constantfile << "SCENE_PROP      = 15<<56\n";
	constantfile << "SOUND           = 16<<56\n";
	constantfile << "MICON           = 18<<56\n";
	constantfile << "SKILL           = 19<<56\n";
	constantfile << "MESH            = 20<<56\n";
	constantfile << "PRESENTATION    = 21<<56\n";
	constantfile << "QSTR            = 22<<56\n";
	constantfile << "MUSIC	       = 23<<56\n";
	constantfile << "TABLEAU         = 24<<56\n";
	constantfile << "ACTION          = 25<<56\n" << endl << endl;
}
void LoadListFile(string path,vector<string> &svector){
	ifstream ifs;
	ifs.open(path);
	if (!ifs)  
	{  
		cout<<"错误：打开文件 "<<path<<" 失败"<<endl;
		cout<<"程序运行需要该txt，请把程序放在mod目录下，或将mod目录中的所有txt复制到程序目录下。"<<endl;
		_getch();
		return;  
	}
	string tempLine;
	while(!ifs.eof()){
		getline(ifs,tempLine);
		if(!tempLine.empty())
			svector.push_back(tempLine);
	}
}
void conversationmerge(){
	ifstream dlgfile_new("conversation_new.txt");
	ifstream dlgfile_old("conversation_old.txt");
	vector<string> dlgdata_new;
	vector<string> dlgdata_old;
	string csvfile;
	string tstring;
	vector<string> v_tstring;

	getline(dlgfile_new, tstring); 
	getline(dlgfile_new, tstring);
	while (getline(dlgfile_new, tstring)){
		trim(tstring);
		if (tstring.empty())
			continue;
		v_tstring.clear();
		split(tstring, " ", v_tstring);
		dlgdata_new.push_back(v_tstring[0]);
	}

	getline(dlgfile_old, tstring);
	getline(dlgfile_old, tstring);
	while (getline(dlgfile_old, tstring)){
		trim(tstring);
		if (tstring.empty())
			continue;
		v_tstring.clear();
		split(tstring, " ", v_tstring);
		dlgdata_old.push_back(v_tstring[0]);
	}

	if (dlgdata_new.size() != dlgdata_old.size()){
		cout << "警告：新旧conversation.txt中数量等，请检查" << endl;
		return;
	}

	ifstream csv("dialogs.csv");
	while (getline(csv, tstring)){
		trim(tstring);
		if (tstring.empty())
			continue;
		csvfile = csvfile + tstring + "\n";
	}

	for (size_t i = 0; i < dlgdata_new.size(); i++){
		if (dlgdata_new[i] != dlgdata_old[i]){
			int pos;
			if ((pos = csvfile.find(dlgdata_old[i]+"|")) != string::npos)
				csvfile.replace(pos, dlgdata_old[i].length()+1, dlgdata_new[i]+"|");
		}
	}

	ofstream csvnew("dialogs.csv.new");
	csvnew << csvfile;
}
vector<string> default_states;
int initdialogstate(){
	default_states = { "start", "party_encounter", "prisoner_liberated", "enemy_defeated", "party_relieved", "event_triggered", "close_window", "trade", "exchange_members", "trade_prisoners", "buy_mercenaries", "view_char", "training", "member_chat", "prisoner_chat" };
	return 1;
}
int _tmain(int argc, _TCHAR* argv[])
{
	//模式选择
	cout << "选择一个模式" << endl;
	cout << "0.反编译模式，此模式生成的py文件可以直接丢Module System编译" << endl;
	cout << "1.注释模式，此模式会将TROOP+xxx解析为trp_xxx字符串，但不可以直接编译" << endl;
	cout << "2.合并conversation.txt，用于修正不规范修改的txt" << endl;
	cout << "请选择模式(输入0/1/2)：";
	scanf("%d", &sel);
	if (sel == 2)
		goto sel2;
	//创建输出文件夹
	_mkdir("reversed");

	//原本打算添加注释，但感觉很麻烦，改用2个模式取代注释。
	//两个模式生成2个文件：一个以常量硬编码用来编译，一个以可读性强的模式用来阅读，两者对照即是注释。
	tempcomment.init();
	
	//初始化各种解析用的map对象
	initmap();

	//输出常量硬编码需要的py文件
	constantfile.open("reversed\\txt2py_constant.py", ios::out);
	outputconstant();

	//初始化预定义的dialogstate
	initdialogstate();

	//载入quickstring，quickstring.txt结构太简单，就不定义对象了，直接读取到list里。
	loadquickstring();
	LoadListFile("variables.txt", gVars);

	//读取，将txt读取到内存中，并存入定义好的结构
	trp_file.load();
	dialogs.load();
	scripts.load();
	triggers.load();
	missions.load();
	menus.load();
	str_file.load();

	//解析，将内存中的数据进行翻译
	trp_file.analyze();
	triggers.analyze();
	scripts.analyze();
	missions.analyze();
	dialogs.analyze();
	menus.analyze();
	
	//将内存中数据输出为py文件
	trp_file.output();   //troop的py文件不可以放进去编译，因为关联太多了，只是一个参考
	menus.output();
	dialogs.output();
	triggers.output();
	missions.output();
	scripts.output();
	str_file.output();

	cout<<endl<<"  *********ALL DONE*********"<<endl<<endl;
	cout<<"反编译后的文件存放在reversed文件夹下"<<endl<<"txt2py_constant.py里定义了一些常量"<<endl;
	cout << "反编译出的module_troops.py不可以拖入ms进行编译，只可以阅读，因为关联太多" << endl;
	cout << "使用方法：将0模式和1模式（类似注释）生成的文件同时打开对照阅读" << endl;
	_getch();
	return 0;
sel2:
	conversationmerge();
	cout << endl << "  *********ALL DONE*********" << endl << endl;
	cout << endl << "  *******生成新的csv文件是dialogs.csv.new*******" << endl << endl;
	_getch();
	return 0;
}

